### ISSUE TITLE
IntegrityError at /account/update_profile/

### ISSUE THREAD

**Issue by DhaiDev** [SelmiAbderrahim/Django-Community-Forum-Website#1]
django.db.utils.IntegrityError: UNIQUE constraint failed: main_author.slug

this error occurred when user upload profile pic

**Comment by SelmiAbderrahim** [comment]
Did you use the code from this repo or did you follow the tuto on YouTube?

**Comment by SelmiAbderrahim** [comment]
This error fixed in the last update, please get the code from the last push.
